app_env: local
allowed_origins:
todo_service: true
host: localhost
port: 8110
context_timeout: 2

mongo:
  db_host: localhost
  db_port: 27017
  db_user: user
  db_pass: pass
  db_name: todo-gateway

memcached:
  db_host: localhost
  db_port: 11211

jwt:
  access_token_expiry_minute: 5
  access_token_secret: access_token_secret

grpc_server:
  network: tcp
  host: localhost
  port: 9000
  tls: false

grpc_client:
  auth_service:
    host: localhost
    port: 9000
    tls: false
  todo_service:
    host: localhost
    port: 9100
    tls: false