app_env: local
allowed_origins:
preference_service: true
invitation_service: true
host: localhost
port: 8110
context_timeout: 2

mongo:
  db_host: localhost
  db_port: 27017
  db_user: user
  db_pass: pass
  db_name: auth-service

memcached:
  db_host: localhost
  db_port: 11211

jwt:
  access_token_expiry_minute: 5
  refresh_token_expiry_minute: 10
  access_token_secret: access_token_secret
  refresh_token_secret: refresh_token_secret

grpc_server:
  network: tcp
  host: localhost
  port: 9000
  tls: false

grpc_client:
  auth_service:
    host: localhost
    port: 9000
    tls: false
  preference_service:
    host: localhost
    port: 9050
    tls: false
  invitation_service:
    host: localhost
    port: 9100
    tls: false