app_env: local
allowed_origins:
todo_service: true
host: todo-gateway
port: 8110
context_timeout: 2

mongo:
  db_host: mongodb
  db_port: 27017
  db_user:
  db_pass:
  db_name: todo-gateway

memcached:
  db_host: memcached
  db_port: 11211

jwt:
  access_token_expiry_minute: 5
  access_token_secret: access_token_secret

grpc_server:
  network: tcp
  host: todo-gateway
  port: 9000
  tls: false

grpc_client:
  auth_service:
    host: todo-gateway
    port: 9000
    tls: false
  todo_service:
    host: todo_service
    port: 9100
    tls: false
